## App URLs
app.url=https://opensource-demo.orangehrmlive.com/

## Valid Credentials
login.username=admin
login.password=admin123

## Invalid Credentials
invalid.login.username=demo234245
invalid.login.password=demo12345